name : first-ci
on: push
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: welcom massage
        run: echo Hello world
      - name: list files
        run : ls -all
      - name: Read Content of readme
        run: cat README.md
